### ISSUE TITLE
Allow using local cache in multiple self-hosted runners

### ISSUE THREAD

**Issue by whalemare** [dhadka/ezcache#20]
In [docs](https://github.com/marketplace/actions/ezcache-caching-made-easy#local) you say: 

```
Stores caches on the local file system. Please note that caches can only be shared between jobs on the same machine. Therefore, avoid using when multiple self-hosted runners are registered or on hosted runners.
```

But, if I have 5 self-hosted runner, that can run workflows parallel, I want that each of this machine use its own cache.
For achieve this, we can provide `key` value, like it [@actions/cache](https://github.com/marketplace/actions/cache) and this problem will gone

**Comment by dhadka** [comment]
> I want that each of this machine use its own cache.

Yes, this is what I was trying to convey in the docs.  Re-reading the last sentence I can see how it's unclear 😄 .  Each machine uses its own local cache.  I'll update those docs.

**Comment by dhadka** [comment]
Updated the text.  Please let me know if there's anything I can clarify further.
